[package]
name = "screen-shot"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
threadpool = "1.8"
chrono = "0.4"
opencv = "0.95.1"
